version: '2'

services:
  db:
    image: postgres:9.6
    container_name: dbps     

    volumes:
      - ./db_files:/var/lib/postgresql/data

    restart: always

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor

    ports:
      - "5432:5432"

  rails:
    image: rails:5.1.4
    container_name: drails     
    depends_on:
      - db
    build:
      context: ./
      dockerfile: DockerFileRails
    links:
      - db
    environment:
      DB_HOST: db:5432
      RAILS_ENV: development
   
    volumes:
      - ./app:/home/rails/app
      - ./bundle:/usr/local/bundle   

    ports:
      - 3000:3000
    tty: true  
